#!/bin/bash

#source venv/bin/activate

python train.py --algo ppo --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo --storage logs/hpo_lunarlander/lunarlander_ppo.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 6
python train.py --algo ppo_mod_advantages --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_mod_advantages --storage logs/hpo_lunarlander/lunarlander_ppo_mod_advantages.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 6
python train.py --algo ppo_mod_sampling --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_mod_sampling --storage logs/hpo_lunarlander/lunarlander_ppo_mod_sampling.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 6
python train.py --algo ppo_changed_before_normalization --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_changed_before_normalization --storage logs/hpo_lunarlander/lunarlander_ppo_changed_before_normalization.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 6

python train.py --algo ppo --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo --storage logs/hpo_lunarlander/lunarlander_ppo.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 7
python train.py --algo ppo_mod_advantages --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_mod_advantages --storage logs/hpo_lunarlander/lunarlander_ppo_mod_advantages.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 7
python train.py --algo ppo_mod_sampling --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_mod_sampling --storage logs/hpo_lunarlander/lunarlander_ppo_mod_sampling.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 7
python train.py --algo ppo_changed_before_normalization --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_changed_before_normalization --storage logs/hpo_lunarlander/lunarlander_ppo_changed_before_normalization.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 7

python train.py --algo ppo --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo --storage logs/hpo_lunarlander/lunarlander_ppo.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 8
python train.py --algo ppo_mod_advantages --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_mod_advantages --storage logs/hpo_lunarlander/lunarlander_ppo_mod_advantages.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 8
python train.py --algo ppo_mod_sampling --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_mod_sampling --storage logs/hpo_lunarlander/lunarlander_ppo_mod_sampling.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 8
python train.py --algo ppo_changed_before_normalization --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_changed_before_normalization --storage logs/hpo_lunarlander/lunarlander_ppo_changed_before_normalization.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 8

python train.py --algo ppo --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo --storage logs/hpo_lunarlander/lunarlander_ppo.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 9
python train.py --algo ppo_mod_advantages --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_mod_advantages --storage logs/hpo_lunarlander/lunarlander_ppo_mod_advantages.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 9
python train.py --algo ppo_mod_sampling --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_mod_sampling --storage logs/hpo_lunarlander/lunarlander_ppo_mod_sampling.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 9
python train.py --algo ppo_changed_before_normalization --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_changed_before_normalization --storage logs/hpo_lunarlander/lunarlander_ppo_changed_before_normalization.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 9

python train.py --algo ppo --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo --storage logs/hpo_lunarlander/lunarlander_ppo.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 0
python train.py --algo ppo_mod_advantages --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_mod_advantages --storage logs/hpo_lunarlander/lunarlander_ppo_mod_advantages.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 0
python train.py --algo ppo_mod_sampling --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_mod_sampling --storage logs/hpo_lunarlander/lunarlander_ppo_mod_sampling.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 0
python train.py --algo ppo_changed_before_normalization --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_changed_before_normalization --storage logs/hpo_lunarlander/lunarlander_ppo_changed_before_normalization.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 0


python train.py --algo ppo_no_clipping --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_no_clipping --storage logs/hpo_lunarlander/lunarlander_ppo_no_clipping.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 2
python train.py --algo ppo_no_clipping --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_no_clipping --storage logs/hpo_lunarlander/lunarlander_ppo_no_clipping.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 3
python train.py --algo ppo_no_clipping --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_no_clipping --storage logs/hpo_lunarlander/lunarlander_ppo_no_clipping.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 4
python train.py --algo ppo_no_clipping --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_no_clipping --storage logs/hpo_lunarlander/lunarlander_ppo_no_clipping.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 5
python train.py --algo ppo_no_clipping --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_no_clipping --storage logs/hpo_lunarlander/lunarlander_ppo_no_clipping.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 6
python train.py --algo ppo_no_clipping --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_no_clipping --storage logs/hpo_lunarlander/lunarlander_ppo_no_clipping.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 7
python train.py --algo ppo_no_clipping --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_no_clipping --storage logs/hpo_lunarlander/lunarlander_ppo_no_clipping.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 8
python train.py --algo ppo_no_clipping --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_no_clipping --storage logs/hpo_lunarlander/lunarlander_ppo_no_clipping.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 9
python train.py --algo ppo_no_clipping --env LunarLander-v3 -n 1000000 --hyperparams gamma:0.998 --study-name lunarlander_ppo_no_clipping --storage logs/hpo_lunarlander/lunarlander_ppo_no_clipping.log --eval-freq 5000 --eval-episodes 5 --track --wandb-project-name "LunarLanderVergleich" --wandb-entity "RL2_2025" -tags "optimized_params" --seed 0

